build:
  environment:
    php:
      version: "8.2"
filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false